export interface Client {
    'Contact ID': string,	
    'First Name': string,
    'Last Name': string,
    'Full Address': string,
    'Client Gender': string,
    'Level of Dependence': string,	
    'Cavergiver Rank': string,	
    'Update date': string,	
    'Additional Instructions': string,	
    'Mobility': string,	
    'District': string,	
    'Medical Condition': string,	
    'Status_': string,	
    'Phone Number': string,	
    'Caregiver Gender': string,	
    'End Date': string,	
    'Service': string,
    'Weight Group': string,	
    'Relationship': string,	
    'Language': string,	
    'Source': string,	
    'Internal Email': string,	
    'Real Email': string,	
    'Client Number': string,	
    "Patient's Name": string,
    'Age Group': string,	
    'Initial Contact': string,	
    'CD - Termination Reason': string,
}